### ISSUE TITLE
react-native-osmdroid doesn't support android

### ISSUE THREAD

**Issue by firepked** [Splicer97/react-native-osmdroid#1]
Hey,

I have trouble to get an Google Maps Key, and I don't really need gmaps.

I've found your module and thought great... but now I get this Errror:

react-native-osmdroid doesn't support android

I was using Expo SDK 44 and older react native, because I have trouble to compile higher Versions due to dependencies missmatch. Compiled Version with SDK was working but crashes when opening original Map View because no API Key is set. Even with WMTS Maps.. great. (So It's not crashing generally) 
 
What ever, I've upgraded to newest Expo SDK 48 and react-native 0.71.6 (since ur using above 0.70 and i was using below)

I still get the Error when I open the Map Component. 

Is the Component not compatible with expo? The Base was I guess

**Comment by Splicer97** [comment]
Hello! This map not use any api key. I'm not sure that you can use this map with Expo. Try with native CLI project.

**Comment by firepked** [comment]
Hey, first of all thank you for the quick answer.

I know that this component does not require an API key.

I have an programmed APP with the Expo Framework. I have difficulties to get an API key from Google.

I have replaced the original Mapview component 1to1 with this one.
It is not possible to debug with Expo GO, however the compiled version seems to work.

I was able to solve the crash I mentioned before by looking at the system log. The cause was as follows:

com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'region' of a view managed by: OsmMap
...
Caused by: com.facebook.react.bridge.NoSuchKeyException: longitudeDelta

For some reason I must have passed an empty object, or an object containing only the latitude and longitude. 

I created a state that I set with a UseEffect on the original location variable and set longitudeDelta/latitudeDelta if it is null/undef. 

Maybe it would be useful to handle this error for other users, since these values only determine the zoom, right?

The app "runs" with this fix before, however radius and other things are not displayed correctly. I'll have to take a closer look at that. Something about the Z-index was also in the readme from you I guess.

For the original problem I don't have a solution yet, probably it will be like you said, however I can't create a native project since the app is already finished.

I'll get back to here if I've found a solution or not.

First of all thanks for your work!

**Comment by firepked** [comment]
I didn't want to close sorry

**Comment by Splicer97** [comment]
> I didn't want to close sorry

Deltas is necessary for this map. Expo Go not working with native libraries like this, you can use expo bare workflow if you want use expo with this library.

**Comment by Splicer97** [comment]
> I didn't want to close sorry

Anyway, Thank you for feedback!
