### ISSUE TITLE
Hi Sir, This is not an issue but rather a question out of my curiosity. Is this API free to use without an API key?

### ISSUE THREAD

**Issue by ronuelbmoralita** [Splicer97/react-native-osmdroid#2]

**Comment by Splicer97** [comment]
Hello! Sure, it's free.

**Comment by ronuelbmoralita** [comment]
> Hello! Sure, it's free.

Good work sir. You know I'm struggling right now and I want to make my own startup but I don't have enough budget. My previous employer's salary did not provide enough room for savings. I'm hoping for some open-source API because Google's service is too expensive. Anyway, Thanks for this Great Libray, God bless.

**Comment by ronuelbmoralita** [comment]
One more question Sir. Can I use this Map Component for mass users? Obviously, you are using UrlTile components, Are there any quotas every time the user requests to get the tile from the server you are using or is there no limit?

**Comment by Splicer97** [comment]
> One more question Sir. Can I use this Map Component for mass users? Obviously, you are using UrlTile components, Are there any quotas every time the user requests to get the tile from the server you are using or is there no limit?

If you don't use custom tiles, there is no limit. In UrlTile component you must use you custom tiles from server, for example maptiler. Maptiler has some quotas.

**Comment by ronuelbmoralita** [comment]
> > One more question Sir. Can I use this Map Component for mass users? Obviously, you are using UrlTile components, Are there any quotas every time the user requests to get the tile from the server you are using or is there no limit?
> 
> If you don't use custom tiles, there is no limit. In UrlTile component you must use you custom tiles from server, for example maptiler. Maptiler has some quotas.

Thanks for the information Sir, have a great day ahead!

**Comment by ronuelbmoralita** [comment]
Hello Sir, it's me again. Does react-native-osmdroid support the showsUserLocation component?

**Comment by ronuelbmoralita** [comment]
Hello, Sir! I've reviewed your code and it appears that the showsUserLocation feature is currently unavailable. Hopefully, this functionality will be included in the next update. I've already implemented my own solution, but it doesn't provide an accurate position.

**Comment by Splicer97** [comment]
> Hello, Sir! I've reviewed your code and it appears that the showsUserLocation feature is currently unavailable. Hopefully, this functionality will be included in the next update. I've already implemented my own solution, but it doesn't provide an accurate position.

Hi, I rarely do not do this library at the moment.  You can send a PR with this feature if you want to improve this library.
